set(_CATKIN_CURRENT_PACKAGE "lf")
set(lf_VERSION "0.0.0")
set(lf_MAINTAINER "vishwajeet <vishwajeet@todo.todo>")
set(lf_PACKAGE_FORMAT "2")
set(lf_BUILD_DEPENDS )
set(lf_BUILD_EXPORT_DEPENDS )
set(lf_BUILDTOOL_DEPENDS "catkin")
set(lf_BUILDTOOL_EXPORT_DEPENDS )
set(lf_EXEC_DEPENDS )
set(lf_RUN_DEPENDS )
set(lf_TEST_DEPENDS )
set(lf_DOC_DEPENDS )
set(lf_URL_WEBSITE "")
set(lf_URL_BUGTRACKER "")
set(lf_URL_REPOSITORY "")
set(lf_DEPRECATED "")