right_leg_v1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yr_r_pel_joint
    - yr_r_hip_joint
    - yr_r_kne_joint
    - yr_r_ank_joint
  gains:
    yr_r_pel_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yr_r_hip_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yr_r_kne_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yr_r_ank_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1