set(_CATKIN_CURRENT_PACKAGE "dikshant_package")
set(dikshant_package_VERSION "0.0.0")
set(dikshant_package_MAINTAINER "vishwajeet <vishwajeet@todo.todo>")
set(dikshant_package_PACKAGE_FORMAT "2")
set(dikshant_package_BUILD_DEPENDS "rospy")
set(dikshant_package_BUILD_EXPORT_DEPENDS "rospy")
set(dikshant_package_BUILDTOOL_DEPENDS "catkin")
set(dikshant_package_BUILDTOOL_EXPORT_DEPENDS )
set(dikshant_package_EXEC_DEPENDS "rospy")
set(dikshant_package_RUN_DEPENDS "rospy")
set(dikshant_package_TEST_DEPENDS )
set(dikshant_package_DOC_DEPENDS )
set(dikshant_package_URL_WEBSITE "")
set(dikshant_package_URL_BUGTRACKER "")
set(dikshant_package_URL_REPOSITORY "")
set(dikshant_package_DEPRECATED "")