// Generated by gencpp from file yr_description/ComputeLeftFootPosition.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_COMPUTELEFTFOOTPOSITION_H
#define YR_DESCRIPTION_MESSAGE_COMPUTELEFTFOOTPOSITION_H

#include <ros/service_traits.h>


#include <yr_description/ComputeLeftFootPositionRequest.h>
#include <yr_description/ComputeLeftFootPositionResponse.h>


namespace yr_description
{

struct ComputeLeftFootPosition
{

typedef ComputeLeftFootPositionRequest Request;
typedef ComputeLeftFootPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeLeftFootPosition
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::ComputeLeftFootPosition > {
  static const char* value()
  {
    return "05815670e17c3341d3dc434a6547e3b1";
  }

  static const char* value(const ::yr_description::ComputeLeftFootPosition&) { return value(); }
};

template<>
struct DataType< ::yr_description::ComputeLeftFootPosition > {
  static const char* value()
  {
    return "yr_description/ComputeLeftFootPosition";
  }

  static const char* value(const ::yr_description::ComputeLeftFootPosition&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::ComputeLeftFootPositionRequest> should match
// service_traits::MD5Sum< ::yr_description::ComputeLeftFootPosition >
template<>
struct MD5Sum< ::yr_description::ComputeLeftFootPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::ComputeLeftFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeLeftFootPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::ComputeLeftFootPositionRequest> should match
// service_traits::DataType< ::yr_description::ComputeLeftFootPosition >
template<>
struct DataType< ::yr_description::ComputeLeftFootPositionRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::ComputeLeftFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeLeftFootPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::ComputeLeftFootPositionResponse> should match
// service_traits::MD5Sum< ::yr_description::ComputeLeftFootPosition >
template<>
struct MD5Sum< ::yr_description::ComputeLeftFootPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::ComputeLeftFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeLeftFootPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::ComputeLeftFootPositionResponse> should match
// service_traits::DataType< ::yr_description::ComputeLeftFootPosition >
template<>
struct DataType< ::yr_description::ComputeLeftFootPositionResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::ComputeLeftFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeLeftFootPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_COMPUTELEFTFOOTPOSITION_H
