// Generated by gencpp from file yr_description/ComputeRightFootPosition.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_COMPUTERIGHTFOOTPOSITION_H
#define YR_DESCRIPTION_MESSAGE_COMPUTERIGHTFOOTPOSITION_H

#include <ros/service_traits.h>


#include <yr_description/ComputeRightFootPositionRequest.h>
#include <yr_description/ComputeRightFootPositionResponse.h>


namespace yr_description
{

struct ComputeRightFootPosition
{

typedef ComputeRightFootPositionRequest Request;
typedef ComputeRightFootPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeRightFootPosition
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::ComputeRightFootPosition > {
  static const char* value()
  {
    return "05815670e17c3341d3dc434a6547e3b1";
  }

  static const char* value(const ::yr_description::ComputeRightFootPosition&) { return value(); }
};

template<>
struct DataType< ::yr_description::ComputeRightFootPosition > {
  static const char* value()
  {
    return "yr_description/ComputeRightFootPosition";
  }

  static const char* value(const ::yr_description::ComputeRightFootPosition&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::ComputeRightFootPositionRequest> should match
// service_traits::MD5Sum< ::yr_description::ComputeRightFootPosition >
template<>
struct MD5Sum< ::yr_description::ComputeRightFootPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::ComputeRightFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeRightFootPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::ComputeRightFootPositionRequest> should match
// service_traits::DataType< ::yr_description::ComputeRightFootPosition >
template<>
struct DataType< ::yr_description::ComputeRightFootPositionRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::ComputeRightFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeRightFootPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::ComputeRightFootPositionResponse> should match
// service_traits::MD5Sum< ::yr_description::ComputeRightFootPosition >
template<>
struct MD5Sum< ::yr_description::ComputeRightFootPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::ComputeRightFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeRightFootPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::ComputeRightFootPositionResponse> should match
// service_traits::DataType< ::yr_description::ComputeRightFootPosition >
template<>
struct DataType< ::yr_description::ComputeRightFootPositionResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::ComputeRightFootPosition >::value();
  }
  static const char* value(const ::yr_description::ComputeRightFootPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_COMPUTERIGHTFOOTPOSITION_H
