// Generated by gencpp from file yr_description/IKRight.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_IKRIGHT_H
#define YR_DESCRIPTION_MESSAGE_IKRIGHT_H

#include <ros/service_traits.h>


#include <yr_description/IKRightRequest.h>
#include <yr_description/IKRightResponse.h>


namespace yr_description
{

struct IKRight
{

typedef IKRightRequest Request;
typedef IKRightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKRight
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::IKRight > {
  static const char* value()
  {
    return "2d3149f50ac2299a08916bb78e0c6b8d";
  }

  static const char* value(const ::yr_description::IKRight&) { return value(); }
};

template<>
struct DataType< ::yr_description::IKRight > {
  static const char* value()
  {
    return "yr_description/IKRight";
  }

  static const char* value(const ::yr_description::IKRight&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::IKRightRequest> should match
// service_traits::MD5Sum< ::yr_description::IKRight >
template<>
struct MD5Sum< ::yr_description::IKRightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::IKRight >::value();
  }
  static const char* value(const ::yr_description::IKRightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::IKRightRequest> should match
// service_traits::DataType< ::yr_description::IKRight >
template<>
struct DataType< ::yr_description::IKRightRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::IKRight >::value();
  }
  static const char* value(const ::yr_description::IKRightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::IKRightResponse> should match
// service_traits::MD5Sum< ::yr_description::IKRight >
template<>
struct MD5Sum< ::yr_description::IKRightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::IKRight >::value();
  }
  static const char* value(const ::yr_description::IKRightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::IKRightResponse> should match
// service_traits::DataType< ::yr_description::IKRight >
template<>
struct DataType< ::yr_description::IKRightResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::IKRight >::value();
  }
  static const char* value(const ::yr_description::IKRightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_IKRIGHT_H
