// Generated by gencpp from file yr_description/JacobianMatrix.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_JACOBIANMATRIX_H
#define YR_DESCRIPTION_MESSAGE_JACOBIANMATRIX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yr_description
{
template <class ContainerAllocator>
struct JacobianMatrix_
{
  typedef JacobianMatrix_<ContainerAllocator> Type;

  JacobianMatrix_()
    : data()
    , rows(0)
    , columns(0)  {
    }
  JacobianMatrix_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , rows(0)
    , columns(0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;

   typedef uint32_t _rows_type;
  _rows_type rows;

   typedef uint32_t _columns_type;
  _columns_type columns;





  typedef boost::shared_ptr< ::yr_description::JacobianMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yr_description::JacobianMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct JacobianMatrix_

typedef ::yr_description::JacobianMatrix_<std::allocator<void> > JacobianMatrix;

typedef boost::shared_ptr< ::yr_description::JacobianMatrix > JacobianMatrixPtr;
typedef boost::shared_ptr< ::yr_description::JacobianMatrix const> JacobianMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yr_description::JacobianMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yr_description::JacobianMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yr_description::JacobianMatrix_<ContainerAllocator1> & lhs, const ::yr_description::JacobianMatrix_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.rows == rhs.rows &&
    lhs.columns == rhs.columns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yr_description::JacobianMatrix_<ContainerAllocator1> & lhs, const ::yr_description::JacobianMatrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yr_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yr_description::JacobianMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yr_description::JacobianMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yr_description::JacobianMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yr_description::JacobianMatrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yr_description::JacobianMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yr_description::JacobianMatrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yr_description::JacobianMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c15edb606601a21cc2f127b349ea452b";
  }

  static const char* value(const ::yr_description::JacobianMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc15edb606601a21cULL;
  static const uint64_t static_value2 = 0xc2f127b349ea452bULL;
};

template<class ContainerAllocator>
struct DataType< ::yr_description::JacobianMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yr_description/JacobianMatrix";
  }

  static const char* value(const ::yr_description::JacobianMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yr_description::JacobianMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data  # Flattened matrix data\n"
"uint32 rows     # Number of rows in the matrix\n"
"uint32 columns  # Number of columns in the matrix\n"
;
  }

  static const char* value(const ::yr_description::JacobianMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yr_description::JacobianMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.rows);
      stream.next(m.columns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacobianMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yr_description::JacobianMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yr_description::JacobianMatrix_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "rows: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rows);
    s << indent << "columns: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.columns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_JACOBIANMATRIX_H
