// Generated by gencpp from file yr_description/SolveIKLeftThigh.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGH_H
#define YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGH_H

#include <ros/service_traits.h>


#include <yr_description/SolveIKLeftThighRequest.h>
#include <yr_description/SolveIKLeftThighResponse.h>


namespace yr_description
{

struct SolveIKLeftThigh
{

typedef SolveIKLeftThighRequest Request;
typedef SolveIKLeftThighResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIKLeftThigh
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::SolveIKLeftThigh > {
  static const char* value()
  {
    return "2d3149f50ac2299a08916bb78e0c6b8d";
  }

  static const char* value(const ::yr_description::SolveIKLeftThigh&) { return value(); }
};

template<>
struct DataType< ::yr_description::SolveIKLeftThigh > {
  static const char* value()
  {
    return "yr_description/SolveIKLeftThigh";
  }

  static const char* value(const ::yr_description::SolveIKLeftThigh&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::SolveIKLeftThighRequest> should match
// service_traits::MD5Sum< ::yr_description::SolveIKLeftThigh >
template<>
struct MD5Sum< ::yr_description::SolveIKLeftThighRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKLeftThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKLeftThighRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKLeftThighRequest> should match
// service_traits::DataType< ::yr_description::SolveIKLeftThigh >
template<>
struct DataType< ::yr_description::SolveIKLeftThighRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKLeftThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKLeftThighRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::SolveIKLeftThighResponse> should match
// service_traits::MD5Sum< ::yr_description::SolveIKLeftThigh >
template<>
struct MD5Sum< ::yr_description::SolveIKLeftThighResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKLeftThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKLeftThighResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKLeftThighResponse> should match
// service_traits::DataType< ::yr_description::SolveIKLeftThigh >
template<>
struct DataType< ::yr_description::SolveIKLeftThighResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKLeftThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKLeftThighResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGH_H
