// Generated by gencpp from file yr_description/SolveIKRightFoot.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTFOOT_H
#define YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTFOOT_H

#include <ros/service_traits.h>


#include <yr_description/SolveIKRightFootRequest.h>
#include <yr_description/SolveIKRightFootResponse.h>


namespace yr_description
{

struct SolveIKRightFoot
{

typedef SolveIKRightFootRequest Request;
typedef SolveIKRightFootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIKRightFoot
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::SolveIKRightFoot > {
  static const char* value()
  {
    return "2d3149f50ac2299a08916bb78e0c6b8d";
  }

  static const char* value(const ::yr_description::SolveIKRightFoot&) { return value(); }
};

template<>
struct DataType< ::yr_description::SolveIKRightFoot > {
  static const char* value()
  {
    return "yr_description/SolveIKRightFoot";
  }

  static const char* value(const ::yr_description::SolveIKRightFoot&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::SolveIKRightFootRequest> should match
// service_traits::MD5Sum< ::yr_description::SolveIKRightFoot >
template<>
struct MD5Sum< ::yr_description::SolveIKRightFootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKRightFoot >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightFootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKRightFootRequest> should match
// service_traits::DataType< ::yr_description::SolveIKRightFoot >
template<>
struct DataType< ::yr_description::SolveIKRightFootRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKRightFoot >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightFootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::SolveIKRightFootResponse> should match
// service_traits::MD5Sum< ::yr_description::SolveIKRightFoot >
template<>
struct MD5Sum< ::yr_description::SolveIKRightFootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKRightFoot >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightFootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKRightFootResponse> should match
// service_traits::DataType< ::yr_description::SolveIKRightFoot >
template<>
struct DataType< ::yr_description::SolveIKRightFootResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKRightFoot >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightFootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTFOOT_H
