// Generated by gencpp from file yr_description/SolveIKRightThigh.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTTHIGH_H
#define YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTTHIGH_H

#include <ros/service_traits.h>


#include <yr_description/SolveIKRightThighRequest.h>
#include <yr_description/SolveIKRightThighResponse.h>


namespace yr_description
{

struct SolveIKRightThigh
{

typedef SolveIKRightThighRequest Request;
typedef SolveIKRightThighResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIKRightThigh
} // namespace yr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yr_description::SolveIKRightThigh > {
  static const char* value()
  {
    return "2d3149f50ac2299a08916bb78e0c6b8d";
  }

  static const char* value(const ::yr_description::SolveIKRightThigh&) { return value(); }
};

template<>
struct DataType< ::yr_description::SolveIKRightThigh > {
  static const char* value()
  {
    return "yr_description/SolveIKRightThigh";
  }

  static const char* value(const ::yr_description::SolveIKRightThigh&) { return value(); }
};


// service_traits::MD5Sum< ::yr_description::SolveIKRightThighRequest> should match
// service_traits::MD5Sum< ::yr_description::SolveIKRightThigh >
template<>
struct MD5Sum< ::yr_description::SolveIKRightThighRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKRightThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightThighRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKRightThighRequest> should match
// service_traits::DataType< ::yr_description::SolveIKRightThigh >
template<>
struct DataType< ::yr_description::SolveIKRightThighRequest>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKRightThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightThighRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yr_description::SolveIKRightThighResponse> should match
// service_traits::MD5Sum< ::yr_description::SolveIKRightThigh >
template<>
struct MD5Sum< ::yr_description::SolveIKRightThighResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yr_description::SolveIKRightThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightThighResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yr_description::SolveIKRightThighResponse> should match
// service_traits::DataType< ::yr_description::SolveIKRightThigh >
template<>
struct DataType< ::yr_description::SolveIKRightThighResponse>
{
  static const char* value()
  {
    return DataType< ::yr_description::SolveIKRightThigh >::value();
  }
  static const char* value(const ::yr_description::SolveIKRightThighResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_SOLVEIKRIGHTTHIGH_H
