// Generated by gencpp from file yr_description/SolveIKLeftThighResponseResponse.msg
// DO NOT EDIT!


#ifndef YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGHRESPONSERESPONSE_H
#define YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGHRESPONSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace yr_description
{
template <class ContainerAllocator>
struct SolveIKLeftThighResponseResponse_
{
  typedef SolveIKLeftThighResponseResponse_<ContainerAllocator> Type;

  SolveIKLeftThighResponseResponse_()
    : foot_position()  {
    }
  SolveIKLeftThighResponseResponse_(const ContainerAllocator& _alloc)
    : foot_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _foot_position_type;
  _foot_position_type foot_position;





  typedef boost::shared_ptr< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SolveIKLeftThighResponseResponse_

typedef ::yr_description::SolveIKLeftThighResponseResponse_<std::allocator<void> > SolveIKLeftThighResponseResponse;

typedef boost::shared_ptr< ::yr_description::SolveIKLeftThighResponseResponse > SolveIKLeftThighResponseResponsePtr;
typedef boost::shared_ptr< ::yr_description::SolveIKLeftThighResponseResponse const> SolveIKLeftThighResponseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator1> & lhs, const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.foot_position == rhs.foot_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator1> & lhs, const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yr_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "877ea7c2b80fdb8aa336bbc2f43238ae";
  }

  static const char* value(const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x877ea7c2b80fdb8aULL;
  static const uint64_t static_value2 = 0xa336bbc2f43238aeULL;
};

template<class ContainerAllocator>
struct DataType< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yr_description/SolveIKLeftThighResponseResponse";
  }

  static const char* value(const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"geometry_msgs/Point foot_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.foot_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolveIKLeftThighResponseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yr_description::SolveIKLeftThighResponseResponse_<ContainerAllocator>& v)
  {
    s << indent << "foot_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YR_DESCRIPTION_MESSAGE_SOLVEIKLEFTTHIGHRESPONSERESPONSE_H
