// Generated by gencpp from file stairs_detection/stair_info.msg
// DO NOT EDIT!


#ifndef STAIRS_DETECTION_MESSAGE_STAIR_INFO_H
#define STAIRS_DETECTION_MESSAGE_STAIR_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace stairs_detection
{
template <class ContainerAllocator>
struct stair_info_
{
  typedef stair_info_<ContainerAllocator> Type;

  stair_info_()
    : pose()
    , step_width(0.0)
    , step_height(0.0)
    , step_length(0.0)
    , is_ascent(false)  {
    }
  stair_info_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , step_width(0.0)
    , step_height(0.0)
    , step_length(0.0)
    , is_ascent(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _step_width_type;
  _step_width_type step_width;

   typedef double _step_height_type;
  _step_height_type step_height;

   typedef double _step_length_type;
  _step_length_type step_length;

   typedef uint8_t _is_ascent_type;
  _is_ascent_type is_ascent;





  typedef boost::shared_ptr< ::stairs_detection::stair_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stairs_detection::stair_info_<ContainerAllocator> const> ConstPtr;

}; // struct stair_info_

typedef ::stairs_detection::stair_info_<std::allocator<void> > stair_info;

typedef boost::shared_ptr< ::stairs_detection::stair_info > stair_infoPtr;
typedef boost::shared_ptr< ::stairs_detection::stair_info const> stair_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stairs_detection::stair_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stairs_detection::stair_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stairs_detection::stair_info_<ContainerAllocator1> & lhs, const ::stairs_detection::stair_info_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.step_width == rhs.step_width &&
    lhs.step_height == rhs.step_height &&
    lhs.step_length == rhs.step_length &&
    lhs.is_ascent == rhs.is_ascent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stairs_detection::stair_info_<ContainerAllocator1> & lhs, const ::stairs_detection::stair_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stairs_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stairs_detection::stair_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stairs_detection::stair_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stairs_detection::stair_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stairs_detection::stair_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stairs_detection::stair_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stairs_detection::stair_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stairs_detection::stair_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51b1f35e0c993fc5f498ebf9309e69d5";
  }

  static const char* value(const ::stairs_detection::stair_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51b1f35e0c993fc5ULL;
  static const uint64_t static_value2 = 0xf498ebf9309e69d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::stairs_detection::stair_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stairs_detection/stair_info";
  }

  static const char* value(const ::stairs_detection::stair_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stairs_detection::stair_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StairStep.msg\n"
"geometry_msgs/PoseStamped pose\n"
"float64 step_width\n"
"float64 step_height\n"
"float64 step_length\n"
"bool is_ascent\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::stairs_detection::stair_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stairs_detection::stair_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.step_width);
      stream.next(m.step_height);
      stream.next(m.step_length);
      stream.next(m.is_ascent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stair_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stairs_detection::stair_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stairs_detection::stair_info_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "step_width: ";
    Printer<double>::stream(s, indent + "  ", v.step_width);
    s << indent << "step_height: ";
    Printer<double>::stream(s, indent + "  ", v.step_height);
    s << indent << "step_length: ";
    Printer<double>::stream(s, indent + "  ", v.step_length);
    s << indent << "is_ascent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_ascent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAIRS_DETECTION_MESSAGE_STAIR_INFO_H
