# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yr_description/FeetPositions.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class FeetPositions(genpy.Message):
  _md5sum = "d71882dfd7fa607b1ca2fb34f4c223ba"
  _type = "yr_description/FeetPositions"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point left_foot
geometry_msgs/Point right_foot
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['left_foot','right_foot']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_foot,right_foot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FeetPositions, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_foot is None:
        self.left_foot = geometry_msgs.msg.Point()
      if self.right_foot is None:
        self.right_foot = geometry_msgs.msg.Point()
    else:
      self.left_foot = geometry_msgs.msg.Point()
      self.right_foot = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.left_foot.x, _x.left_foot.y, _x.left_foot.z, _x.right_foot.x, _x.right_foot.y, _x.right_foot.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.left_foot is None:
        self.left_foot = geometry_msgs.msg.Point()
      if self.right_foot is None:
        self.right_foot = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.left_foot.x, _x.left_foot.y, _x.left_foot.z, _x.right_foot.x, _x.right_foot.y, _x.right_foot.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.left_foot.x, _x.left_foot.y, _x.left_foot.z, _x.right_foot.x, _x.right_foot.y, _x.right_foot.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.left_foot is None:
        self.left_foot = geometry_msgs.msg.Point()
      if self.right_foot is None:
        self.right_foot = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.left_foot.x, _x.left_foot.y, _x.left_foot.z, _x.right_foot.x, _x.right_foot.y, _x.right_foot.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
